spring:
  profile: dev
  devtools.livereload.enabled: true

icaptor:
  data-source:
    host: http://icaptor-data:8085
  broker:
    user: guest
    pass: guest
    host: localhost
    port: 15672
    queue-send-schedular-time: 5000 #milli second
  elasticSearch: http://52.67.200.181:9200

