spring:
  profiles.active: dev
---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false

spring:
  profiles: dev

server:
  name: icaptor-web-server
  host: localhost
  port: 8014


icaptor:
  seguranca:
    enable-https: false
  origin-permitida: http://localhost:4200
  elasticSearch: http://54.232.96.63:9200
---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: false

spring:
  profiles: local

server:
  name: icaptor-web-server
  host: localhost
  port: 8014


icaptor:
  seguranca:
    enable-https: false
  origin-permitida: http://localhost:4200
  elasticSearch: http://54.232.96.63:9200

---

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://54.232.96.63:8761/eureka}
  instance:
    preferIpAddress: true

server:
  name: icaptor-web-server
  host: localhost
  port: 8014

icaptor:
  seguranca:
    enable-https: false
  origin-permitida: http://54.232.96.63
  elasticSearch: http://54.232.96.63:9200

spring:
  profiles: qa