spring:
  profiles.active: local
#logging:
#  config: classpath:logback.xml
---
spring:
  profiles: stage
  redis:
    hostname: 18.231.43.79
    port: 6379
server:
  port : 8086
  servlet-path: /

---
spring:
  profiles: local
  redis:
    hostname: localhost
    port: 6379
server:
  port : 8086
  servlet-path: /

---
spring:
  profiles: qa
  redis:
      hostname: 18.231.43.79
      port: 6379
server:
  port : 8086
  servlet-path: /
