server:
  name: icaptor-web-server
  host: localhost
  port: 8014

management.security.enabled: false


icaptor:
  data-source.host: http://18.231.116.132:8085
  redis: http://18.231.116.132:8086
  server:
    name: icaptor-server
    ip: 127.0.0.1
    host: http://18.231.116.132:8082
  broker:
    user: guest
    pass: guest
    host: 18.231.80.133
    port: 15672
    queue-send-schedular-time: 5000 #milli second
  elasticSearch: http://18.231.80.133:9200
  turn.on.elasticSearch: false
  seguranca:
    enable-https: false
  origin-permitida: http://18.231.120.1
  monitoring: http://18.231.116.132:8090

spring:
    http:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB

management:
  security.enabled: false
  context-path: /management

endpoints:
   logfile:
      sensitive: false
   restart.enabled: true
   info:
      enabled: true
      id: information
logging:
    file: ${user.home}/logs/${spring.application.name}.log