server:
  name: icaptor-monitoring
  host: localhost
  port: 8090

io:
  worker.dir: ${HOME}/.icaptor-agent
  worker.file: ${HOME}/.icaptor-out-file
  file-read: ${HOME}/.icaptor-read-file

icaptor:
  broker:
    user: guest
    pass: guest
    host: localhost
    port: 30001
    queue-send-schedular-time: 5000 #milli second
---
spring:
  profiles:
    active: qa
server:
  name: icaptor-monitoring
  host: localhost
  port: 8090

io:
  worker.dir: ${HOME}/.icaptor-agent
  worker.file: ${HOME}/.icaptor-out-file
  file-read: ${HOME}/.icaptor-read-file

icaptor:
  elasticSearch: http://54.232.136.130:9200
  broker:
    user: guest
    pass: guest
    host: icaptor-broker
    port: 15672
    queue-send-schedular-time: 5000 #milli second
