spring:
  profiles.active: local
#logging:
#  config: classpath:logback.xml
---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://18.231.43.79:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  profiles: stage
  redis:
    hostname: 18.231.43.79
    port: 6379
server:
  port : 8086
  servlet-path: /

---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  profiles: local
  redis:
    hostname: localhost
    port: 6379
server:
  port : 8086
  servlet-path: /

---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://18.231.43.79:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  profiles: qa
  redis:
      hostname: 18.231.43.79
      port: 6379
server:
  port : 8086
  servlet-path: /
