server:
  host: localhost
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/icaptor?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 5
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
#    properties.hibernate.enable_lazy_load_no_trans: true

  jackson:
    serialization.fail-on-empty-beans: false
    deserialization.fail-on-unknown-properties: true
    date-format: dd/MM/yyyy

  data.rest.detection-strategy: annotated
  profile: dev

flyway:
    enabled: "true"
    validateOnMigrate: true

management:
  security.enabled: false
  context-path: /management


#info.app:
#  name: @project.name@
#  description: @project.description@
#  build: @project.version@
#  java.version: @java.specification.version@

endpoints:
  info:
    enabled: true
    id: information


icaptor:
  seguranca:
    enable-https: false
  origin-permitida: http://localhost:4200
  data-source:
    host: http://localhost:8085
  server:
    host: http://localhost:8082
  elasticSearch: http://52.67.200.181:9200
  redis: http://localhost:8086
