server:
  name: icaptor-web-server
  host: localhost
  port: 8014

management.security.enabled: false


icaptor:
  data-source.host: http://icaptor-data:8085
  redis: http://icaptor-redis:8086
  server:
    name: icaptor-server
    ip: 127.0.0.1
    host: http://icaptor-cloud:8082
  broker:
    user: guest
    pass: guest
    host: 52.67.200.181
    port: 15672
    queue-send-schedular-time: 5000 #milli second
  elasticSearch: http://52.67.200.181:9200
  turn.on.elasticSearch: false
  seguranca:
    enable-https: false
  origin-permitida: http://18.231.82.104

spring:
    http:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB
