spring:
  profiles.active: local
---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false

spring:
  profiles: local

server:
  name: icaptor-server
  host: localhost
  port: 8082

io:
  worker.dir: ${user.home}/.icaptor-agent
  worker.file: ${user.home}/.icaptor-out-file
  file-read: ${user.home}/.icaptor-read-file


icaptor:
  broker:
    user: guest
    pass: guest
    host: localhost
    port: 15672
    queue-send-schedular-time: 5000 #milli second
  elasticSearch: http://54.232.136.130:9200



---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://18.231.43.79:8761/eureka}
  instance:
    preferIpAddress: true

server:
  name: icaptor-server
  host: localhost
  port: 8082

spring:
  profiles: qa

io:
  worker.dir: ${user.home}/.icaptor-agent
  worker.file: ${user.home}/.icaptor-out-file
  file-read: ${user.home}/.icaptor-read-file


icaptor:
  broker:
    user: guest
    pass: guest
    host: 18.231.43.79
    port: 15672
    queue-send-schedular-time: 5000 #milli second
  elasticSearch: http://54.232.136.130:9200
