server:
  name: icaptor-web-server
  host: localhost
  port: 8014

management.security.enabled: false


icaptor:
  data-source.host: http://52.67.141.87:8085
  redis: http://52.67.141.87:8086
  server:
    name: icaptor-server
    ip: 127.0.0.1
    host: http://52.67.141.87:8082
  broker:
    user: guest
    pass: guest
    host: 52.67.200.181
    port: 15672
    queue-send-schedular-time: 5000 #milli second
  elasticSearch: http://52.67.200.181:9200
  turn.on.elasticSearch: false
  seguranca:
    enable-https: false
  origin-permitida: http://localhost:4200,http://18.231.82.104,http://177.53.16.82:4200
  monitoring: http://52.67.141.87:8090

spring:
    http:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB

management:
  security.enabled: false
  context-path: /management

endpoints:
   logfile:
      sensitive: false
   restart.enabled: true
   info:
      enabled: true
      id: information
logging:
    file: ${user.home}/logs/${spring.application.name}.log