spring:
  profiles.active: dev
#logging:
#  config: classpath:logback.xml

---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  profiles: dev
  redis:
    hostname: localhost
    port: 6379
server:
  port : 8086
  servlet-path: /

---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  profiles: local
  redis:
    hostname: icaptor-alpine-redis
    port: 6379
server:
  port : 8086
  servlet-path: /

---
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://54.232.96.63:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  profiles: qa
  redis:
      hostname: 54.232.96.63
      port: 6379
server:
  port : 8086
  servlet-path: /
