spring:
  profiles.active: dev
#logging:
#  config: classpath:logback-spring.xml
---
spring:
  profiles: qa
  redis:
    hostname: 52.67.200.181
    port: 6379
server:
  port : 8086
  servlet-path: /

---
spring:
  profiles: dev
  redis:
    hostname: localhost
    port: 6379
server:
  port : 8086
  servlet-path: /

---
spring:
  profiles: test
  redis:
      hostname: localhost
      port: 6379
server:
  port : 8086
  servlet-path: /

---
spring:
  profiles: votorantim
  redis:
      hostname: 52.67.200.181
      port: 6379
server:
  port : 8086
  servlet-path: /