server:
  name: icaptor-web-server
  host: localhost
  port: 8014


icaptor:
  seguranca:
    enable-https: false
  origin-permitida: http://localhost:4200
  elasticSearch: http://54.232.136.130:9200

---
server:
  name: icaptor-web-server
  host: localhost
  port: 8014

icaptor:
  seguranca:
    enable-https: false
  origin-permitida: http://localhost:4200
  elasticSearch: http://54.232.136.130:9200

spring:
  profiles:
    active: qa