spring:
  profiles.active: dev

server:
  name: icaptor-monitoring
  host: localhost
  port: 8090

io:
  worker.dir: ${HOME}/.icaptor-agent
  worker.file: ${HOME}/.icaptor-out-file
  file-read: ${HOME}/.icaptor-read-file

spring:
  profile: dev

icaptor:
  data-source:
    host: http://icaptor-data:8085
  broker:
    user: guest
    pass: guest
    host: icaptor-broker
    port: 15672
    queue-send-schedular-time: 5000 #milli second