---
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:fiveware-solutions/configData.git
server:
  port: 8888

# For simplicity, disable security when posting to bus/refresh:
management:
  security:
    enabled: false